version: '3.8'

services:
  user-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map port 5000 of the container to port 5000 on the host
    environment:
      MONGO_URI: mongodb://mongo:27017/user-management # Connection string for MongoDB
    depends_on:
      - mongo # Ensure MongoDB starts before the user service

  mongo:
    image: mongo:latest # Use the official MongoDB image
    ports:
      - "27017:27017" # Expose MongoDB port
    volumes:
      - mongo-data:/data/db # Use a named volume to persist data

volumes:
  mongo-data: # Define the named volume for MongoDB
